apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - model-deploy.yaml
  - model-service.yaml
  - streamlit-deploy.yaml
  - streamlit-service.yaml
  - fastapi-scaledobject.yaml
