apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: akataya90/streamlit:v2
        name: streamlit
        ports:
        - containerPort: 8501
        resources: {}
status: {}
